[package]
name = "rust_day12"
description = "Full shape fitting solution in Rust for day 12 of Advent of Code 2025"
version = "1.0.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }